# This dockerfile is used to build a docker image for the database and is
# used by the docker-compose.yml file in the root of the project.
FROM postgres:14 AS db
WORKDIR /usr/src/app
# Copy the seed data, and scripts
COPY ./data/*.csv data/
COPY reset.sql .
# Place the seed script in the docker-entrypoint-initdb.d folder so that it
# will be run when the container is started.
COPY docker-seed.sh /docker-entrypoint-initdb.d/
